//! Askama-based template renderer. Pre-formats product data (ARS price, href,
//! brand split) and renders hand-written templates under `tests/templates/`.
//! Autoescape is ON, so raw names are passed. Templates are auto-discovered
//! at compile time via `build.rs` – every top-level `NN_*.html` file is a
//! template (sorted alphabetically), so no manual `0 => "…"` line is needed.

use askama::Template;
use price_hunter_core::detect::Product;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/// Groups an integer digit string in thousands: "328000" -> "328.000".
fn group_thousands(digits: &str) -> String {
    let mut out = String::new();
    let mut count = 0;
    for ch in digits.chars().rev() {
        if count == 3 {
            out.push('.');
            count = 0;
        }
        out.push(ch);
        count += 1;
    }
    let grouped: String = out.chars().rev().collect();
    grouped.strip_prefix('.').unwrap_or(&grouped).to_string()
}

/// ARS formatting: 328000 -> "328.000", 4564.91 -> "4.564,91"
pub fn format_ars(price: f64) -> String {
    let cents = (price * 100.0).round() as i64;
    let int_part = cents / 100;
    let frac = (cents % 100).abs();
    let mut int_formatted = group_thousands(&int_part.abs().to_string());
    if int_part == 0 {
        int_formatted = "0".to_string();
    }
    if frac != 0 {
        format!("{int_formatted},{frac:02}")
    } else {
        int_formatted
    }
}

fn brand_split(name: &str) -> Option<(String, String)> {
    let mut parts = name.split_whitespace();
    let first = parts.next()?;
    let rest: Vec<&str> = parts.collect();
    if rest.is_empty() {
        return None;
    }
    Some((first.to_string(), rest.join(" ")))
}

fn slugify(name: &str) -> String {
    name.to_lowercase()
        .replace(|c: char| !c.is_alphanumeric(), "-")
        .replace("--", "-")
}

#[derive(Debug, Clone)]
pub struct ProductView {
    pub name: String,
    pub name_rest: String,
    pub brand: String,
    pub price_text: String,
    pub href: String,
    pub img: String,
    pub card_class: String,
}

fn to_view(p: &Product, idx: usize) -> ProductView {
    let price_text = format_ars(p.price);
    let slug = slugify(&p.name);
    let href = format!("/producto/{slug}-{idx}/p");
    let img = format!("/img/{idx}.jpg");
    let card_classes = [
        "vtex-product-summary-2-x-container vtex-product-summary-2-x-containerNormal",
        "product-item",
        "card",
        "vtex-search-result-3-x-galleryItem--normal",
    ];
    let card_class = card_classes[idx % card_classes.len()].to_string();
    let (brand, name_rest) =
        brand_split(&p.name).unwrap_or((String::new(), p.name.clone()));
    ProductView {
        name: p.name.clone(),
        name_rest,
        brand,
        price_text,
        href,
        img,
        card_class,
    }
}

// ---------------------------------------------------------------------------
// Auto-discovered templates – generated by build.rs from top-level
// tests/templates/NN_*.html (sorted, numeric prefix required)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/templates_gen.rs"));

#[cfg(test)]
mod tests {
    use super::format_ars;

    #[test]
    fn format_ars_smoke() {
        for (price, expected) in [
            (328000.0, "328.000"),
            (4564.91, "4.564,91"),
            (3744.05, "3.744,05"),
            (95400.0, "95.400"),
            (500.0, "500"),
            (1234.56, "1.234,56"),
        ] {
            assert_eq!(format_ars(price), expected);
        }
    }
}
