//! Use cases: fuzzy-match provider products to canonical products
//! (`match_products`, `link_matches`).

use std::collections::{HashMap, HashSet};

use crate::reporter::Reporter;
use crate::error::PriceStoreError;
use crate::matching::{
    MIN_SCORE, MatchCandidate, PreparedProduct, PreparedProvider, assign_group, brand_from_name,
    brand_key, dice_normalized, plan_candidates, pp_match_key, prepare_name,
};
use crate::model::{BrandRow, MatchInsert, ProductRow, ProviderProductRow};
use crate::ports::PriceStore;

/// Outcome of one `-match-products` run.
#[derive(Debug)]
pub struct MatchSummary {
    /// New comparison rows stored (only pairs scored at or above `MIN_SCORE`
    /// are written; weaker pairs are scored but not kept).
    pub computed: usize,
    /// Comparisons already present from a previous run (skipped).
    pub already_stored: usize,
    /// Provider products considered for linking.
    pub provider_products: usize,
    /// Provider products linked to a canonical product.
    pub matched: usize,
    /// Candidate pairs that reached the exact Dice computation (after brand
    /// partition + bigram prefix + length filtering).
    pub evaluated: usize,
    /// Pairs pruned without scoring (`total - evaluated`, where total is
    /// `providers * products`).
    pub skipped: usize,
}

/// Outcome of one `-link-matches` run (no backfill).
#[derive(Debug)]
pub struct LinkSummary {
    /// Provider products considered for linking.
    pub provider_products: usize,
    /// Provider products linked to a canonical product.
    pub matched: usize,
}

/// Runs the fuzzy matcher between provider products and canonical
/// products. Candidate (provider product, canonical product) pairs are
/// generated by brand partitioning plus a bigram prefix filter (see
/// [`plan_candidates`]); only candidates reach the exact Dice computation,
/// and pairs at or above `MIN_SCORE` are stored in
/// `provider_product_matches` (weaker scores are recomputed on a later run,
/// never cached). Pairs already stored on a previous run are skipped, and
/// each new score is written immediately (one insert at a time) so a crash
/// never loses progress. After the backfill, the best match per provider
/// product is linked (per-provider exclusivity) using the stored scores at
/// or above `MIN_SCORE`. Progress is reported through `reporter` over the
/// candidate pairs (not the full cross product).
///
/// Brand note: two *known, different* brands are never compared (run
/// `-match-brands` first so provider brands are populated). Provider
/// products and canonical products with an unknown brand are compared
/// against every brand group, so no recall is lost there.
pub fn match_products(
    store: &impl PriceStore,
    reporter: &mut dyn Reporter,
) -> Result<MatchSummary, PriceStoreError> {
    let products = store.list_products()?;
    let provider_products = store.list_provider_products()?;
    let brands = store.list_brands()?;

    let stored = store.list_all_matches(&provider_products)?;
    let mut stored_pairs: HashSet<(String, String)> = stored
        .iter()
        .map(|r| (r.provider_product_id.clone(), r.product_id.clone()))
        .collect();
    let mut candidates: Vec<MatchCandidate> = stored
        .iter()
        .filter(|r| r.score >= MIN_SCORE)
        .map(|r| MatchCandidate {
            provider_product_id: r.provider_product_id.clone(),
            product_id: r.product_id.clone(),
            score: r.score,
        })
        .collect();

    let prepared_providers = prepare_providers(&provider_products, &products, &brands);
    let prepared_products = prepare_products(&products);
    let (pairs, stats) = plan_candidates(&prepared_providers, &prepared_products);
    let mut backfill = CandidateBackfill {
        store,
        provider_products: &provider_products,
        products: &products,
        prepared_providers: &prepared_providers,
        prepared_products: &prepared_products,
        stored_pairs: &mut stored_pairs,
        candidates: &mut candidates,
        reporter,
    };
    let computed = backfill.run(&pairs)?;
    let (matched, total) = finish_linking(store, &provider_products, &candidates)?;

    Ok(MatchSummary {
        computed,
        already_stored: stored.len(),
        provider_products: total,
        matched,
        evaluated: stats.scored,
        skipped: stats.total_pairs.saturating_sub(stats.scored),
    })
}

/// Precomputes one comparison entry per canonical product (display-name key
/// plus brand group; `""` = unknown brand).
fn prepare_products(products: &[ProductRow]) -> Vec<PreparedProduct> {
    products
        .iter()
        .enumerate()
        .map(|(index, product)| PreparedProduct {
            index,
            name: prepare_name(&product.name),
            brand: brand_key(&product.brand),
        })
        .collect()
}

/// Precomputes one comparison entry per provider product (size-stripped name
/// key plus resolved brand; `None` = unknown brand, compared against every
/// group). Brand resolution, in order: the linked product's brand, the
/// assigned `brand_id` via the brand table, the raw `brand_name` matched
/// exactly against the brand table, then a fuzzy brand guessed from the
/// name. Anything unresolved stays unknown (full scan, no recall lost).
fn prepare_providers(
    provider_products: &[ProviderProductRow],
    products: &[ProductRow],
    brands: &[BrandRow],
) -> Vec<PreparedProvider> {
    let brand_name_by_id: HashMap<&str, &str> = brands
        .iter()
        .map(|b| (b.id.as_str(), b.name.as_str()))
        .collect();
    let product_brand_by_id: HashMap<&str, &str> = products
        .iter()
        .map(|p| (p.id.as_str(), p.brand.as_str()))
        .collect();
    let table_keys: HashMap<String, String> = brands
        .iter()
        .map(|b| (brand_key(&b.name), brand_key(&b.name)))
        .collect();
    let brand_candidates: Vec<(String, String)> = brands
        .iter()
        .map(|b| (b.id.clone(), b.name.clone()))
        .collect();
    provider_products
        .iter()
        .enumerate()
        .map(|(index, pp)| PreparedProvider {
            index,
            name: prepare_name(&pp_match_key(&pp.name)),
            brand: resolve_provider_brand(
                pp,
                &product_brand_by_id,
                &brand_name_by_id,
                &table_keys,
                &brand_candidates,
            ),
        })
        .collect()
}

/// Resolves one provider product to a canonical brand key (`None` unknown).
fn resolve_provider_brand(
    pp: &ProviderProductRow,
    product_brand_by_id: &HashMap<&str, &str>,
    brand_name_by_id: &HashMap<&str, &str>,
    table_keys: &HashMap<String, String>,
    brand_candidates: &[(String, String)],
) -> Option<String> {
    if let Some(product_id) = pp.product_id.as_deref().filter(|s| !s.is_empty())
        && let Some(brand) = product_brand_by_id.get(product_id)
        && !brand.trim().is_empty()
    {
        return Some(brand_key(brand));
    }
    if let Some(brand_id) = pp.brand_id.as_deref().filter(|s| !s.is_empty())
        && let Some(name) = brand_name_by_id.get(brand_id)
    {
        return Some(brand_key(name));
    }
    if let Some(raw) = pp.brand_name.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        let key = brand_key(raw);
        if table_keys.contains_key(&key) {
            return Some(key);
        }
    }
    brand_from_name(&pp.name, brand_candidates).map(|name| brand_key(&name))
}

/// Re-links provider products to canonical products using only the
/// comparisons already stored in `provider_product_matches` (no backfill).
/// A quick way to refresh links after scraping new data without waiting
/// for the full comparison pass — an interrupted `-match-products` can no
/// longer leave the matrix stale.
pub fn link_matches(store: &impl PriceStore) -> Result<LinkSummary, PriceStoreError> {
    let provider_products = store.list_provider_products()?;
    let candidates = store.list_above_threshold_candidates()?;
    let (matched, total) = finish_linking(store, &provider_products, &candidates)?;
    Ok(LinkSummary {
        provider_products: total,
        matched,
    })
}

/// Clears `product_id` on every provider product and re-assigns winners
/// from `candidates`. Returns `(matched, provider_products)`.
fn finish_linking(
    store: &impl PriceStore,
    provider_products: &[ProviderProductRow],
    candidates: &[MatchCandidate],
) -> Result<(usize, usize), PriceStoreError> {
    let provider_of: HashMap<&str, &str> = provider_products
        .iter()
        .map(|p| (p.id.as_str(), p.provider_id.as_str()))
        .collect();
    store.unlink_all(provider_products)?;
    let matched = link_winners(store, candidates, &provider_of)?;
    Ok((matched, provider_products.len()))
}

/// Scores and stores candidate pairs from [`plan_candidates`], one insert at
/// a time. Only pairs scored at or above `MIN_SCORE` are written and
/// appended to `candidates`. Each new score is written immediately so a crash
/// never loses progress.
struct CandidateBackfill<'a, S: PriceStore> {
    store: &'a S,
    provider_products: &'a [ProviderProductRow],
    products: &'a [ProductRow],
    prepared_providers: &'a [PreparedProvider],
    prepared_products: &'a [PreparedProduct],
    stored_pairs: &'a mut HashSet<(String, String)>,
    candidates: &'a mut Vec<MatchCandidate>,
    reporter: &'a mut dyn Reporter,
}

impl<S: PriceStore> CandidateBackfill<'_, S> {
    /// Scores every `(provider_index, product_index)` pair and returns how
    /// many comparison rows were stored.
    fn run(&mut self, pairs: &[(usize, usize)]) -> Result<usize, PriceStoreError> {
        let total = pairs.len();
        let mut computed = 0;
        for (done, (pp_index, product_index)) in pairs.iter().enumerate() {
            let pp = &self.provider_products[*pp_index];
            let product = &self.products[*product_index];
            let score = dice_normalized(
                &self.prepared_providers[*pp_index].name,
                &self.prepared_products[*product_index].name,
            );
            computed += self.store_pair(&pp.id, &product.id, score)?;
            self.reporter.progress(done + 1, total);
        }
        self.reporter.progress(total, total);
        Ok(computed)
    }

    /// Stores one scored pair unless it is already stored (see [`store_pair`]
    /// for the free function logic).
    fn store_pair(
        &mut self,
        provider_product_id: &str,
        product_id: &str,
        score: f64,
    ) -> Result<usize, PriceStoreError> {
        store_pair(
            self.store,
            provider_product_id,
            product_id,
            score,
            self.stored_pairs,
            self.candidates,
        )
    }
}

/// Stores one scored pair unless it is already stored. Pairs at or above
/// `MIN_SCORE` are written immediately and appended to `candidates`; weaker
/// pairs are scored but not stored. Returns 1 when a new match row was
/// created, 0 otherwise (already cached, or scored below the threshold).
fn store_pair(
    store: &impl PriceStore,
    provider_product_id: &str,
    product_id: &str,
    score: f64,
    stored_pairs: &mut HashSet<(String, String)>,
    candidates: &mut Vec<MatchCandidate>,
) -> Result<usize, PriceStoreError> {
    let pair = (
        provider_product_id.to_string(),
        product_id.to_string(),
    );
    if stored_pairs.contains(&pair) {
        return Ok(0);
    }
    // Only comparisons at or above `MIN_SCORE` are worth keeping: weaker
    // scores are recomputed on a later run instead of accumulating in
    // `provider_product_matches`.
    let created = if score >= MIN_SCORE {
        matches!(
            store.create_match(&pair.0, &pair.1, score)?,
            MatchInsert::Created
        )
    } else {
        false
    };
    stored_pairs.insert(pair);
    if score >= MIN_SCORE {
        candidates.push(MatchCandidate {
            provider_product_id: provider_product_id.to_string(),
            product_id: product_id.to_string(),
            score,
        });
    }
    Ok(usize::from(created))
}

/// Greedily assigns canonical products within each provider group, sets
/// `provider_products.product_id` and marks the winning match row
/// confirmed. Returns the number of provider products linked.
fn link_winners(
    store: &impl PriceStore,
    candidates: &[MatchCandidate],
    provider_of: &HashMap<&str, &str>,
) -> Result<usize, PriceStoreError> {
    let grouped = group_by_provider(candidates, provider_of);
    let mut matched = 0;
    for group in grouped.values() {
        matched += apply_group(store, group)?;
    }
    Ok(matched)
}

/// Groups candidates by their provider id (owned values avoid borrow
/// lifetime juggling).
fn group_by_provider(
    candidates: &[MatchCandidate],
    provider_of: &HashMap<&str, &str>,
) -> HashMap<String, Vec<MatchCandidate>> {
    let mut grouped: HashMap<String, Vec<MatchCandidate>> = HashMap::new();
    for c in candidates {
        if let Some(pid) = provider_of.get(c.provider_product_id.as_str()) {
            grouped
                .entry((*pid).to_string())
                .or_default()
                .push(c.clone());
        }
    }
    grouped
}

/// Assigns and links the winners of one provider group.
fn apply_group(
    store: &impl PriceStore,
    group: &[MatchCandidate],
) -> Result<usize, PriceStoreError> {
    let mut matched = 0;
    for winner in assign_group(group) {
        store.link_product(&winner)?;
        matched += 1;
    }
    Ok(matched)
}
