use std::fs;
use std::path::Path;

fn template_files() -> Vec<String> {
    let dir = Path::new("tests/templates");
    let mut files: Vec<String> = fs::read_dir(dir)
        .expect("tests/templates missing")
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().ok().map(|t| t.is_file()).unwrap_or(false))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| n.ends_with(".html"))
        .filter(|n| n.chars().next().is_some_and(|c| c.is_ascii_digit()))
        .collect();

    files.sort();

    assert_eq!(
        files.len(),
        50,
        "expected 50 top-level numeric templates in tests/templates/*.html, got {}: {:?}",
        files.len(),
        files
    );

    // Validate numeric prefix 00_ etc is present (already filtered digit, check second char)
    for f in &files {
        assert!(
            has_numeric_prefix(f),
            "template {f} must have numeric prefix NN_"
        );
    }

    files
}

fn has_numeric_prefix(name: &str) -> bool {
    name.len() >= 3
        && name.chars().nth(1).is_some_and(|c| c.is_ascii_digit())
        && name.chars().nth(2) == Some('_')
}

fn main() {
    println!("cargo:rerun-if-changed=tests/templates");
    println!("cargo:rerun-if-changed=askama.toml");

    let files = template_files();

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("templates_gen.rs");

    let mut code = String::new();
    code.push_str("// @generated by build.rs – do not edit\n");
    code.push_str("// Top-level *.html only, numeric prefix required, sorted alphabetically\n\n");

    for (idx, path) in files.iter().enumerate() {
        code.push_str(&format!(
            "#[derive(Template)]\n#[template(path = \"{path}\")]\nstruct T{idx:02} {{ products: Vec<ProductView>, }}\n\n"
        ));
    }

    code.push_str(&format!(
        "const TEMPLATES: &[&str; {}] = &[{}];\n\n",
        files.len(),
        files.iter().map(|p| format!("\"{p}\"")).collect::<Vec<_>>().join(", ")
    ));

    code.push_str("pub fn render_template_by_idx(idx: usize, products: &[Product]) -> String {\n");
    code.push_str("    let views: Vec<ProductView> = products.iter().enumerate().map(|(i, p)| to_view(p, i)).collect();\n");
    code.push_str("    match idx % TEMPLATES.len() {\n");
    for idx in 0..files.len() {
        code.push_str(&format!(
            "        {idx} => T{idx:02} {{ products: views }}.render().expect(\"askama render failed\"),\n"
        ));
    }
    code.push_str("        _ => unreachable!(),\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn template_name(idx: usize) -> &'static str {\n");
    code.push_str("    TEMPLATES[idx % TEMPLATES.len()]\n");
    code.push_str("}\n");

    fs::write(&out_path, code).expect("write templates_gen.rs");
}
